name: OmgImageFlow API CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name a Targaryen dragon'
        # Default value if no value is explicitly provided
        default: 'Silverwing'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -o ${{ github.workspace }}/api --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: 'omgimgflow-api-artifact'
        path: ${{ github.workspace }}/api
        retention-days: 1
