name: OmgImageFlow API CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name a Targaryen dragon'
        # Default value if no value is explicitly provided
        default: 'Silverwing'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -o ${{ github.workspace }}/api --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: omgimgflow-api-artifact
        path: ${{ github.workspace }}/api
        retention-days: 1
  
  release:
    name: Release to VPS
    needs: [build]
    strategy:
      matrix:
        kind: ['linux']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          # Artifact name
          name: omgimgflow-api-artifact
          # Destination path
          path: omgimgflow-api
      - name: Create the temp directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LHARGIL_VPS_HOST }}
          port: ${{ secrets.LHARGIL_VPS_DEPLOYER_PORT }}
          username: ${{ secrets.LHARGIL_VPS_DEPLOYER_USERNAME }}
          key: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_KEY }}
          passphrase: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_PASS }}
          script: mkdir -p ${{ secrets.OMGIMGFLOW_API_TEMP_DEST}}
      - name: Transfer the built files to the temp directory
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.LHARGIL_VPS_HOST }}
          port: ${{ secrets.LHARGIL_VPS_DEPLOYER_PORT }}
          username: ${{ secrets.LHARGIL_VPS_DEPLOYER_USERNAME }}
          key: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_KEY }}
          passphrase: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_PASS }}
          source: "omgimgflow-api"
          target: ${{ secrets.OMGIMGFLOW_API_TEMP_DEST}}
      - name: Actually deploy and restart api service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LHARGIL_VPS_HOST }}
          port: ${{ secrets.LHARGIL_VPS_DEPLOYER_PORT }}
          username: ${{ secrets.LHARGIL_VPS_DEPLOYER_USERNAME }}
          key: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_KEY }}
          passphrase: ${{ secrets.LHARGIL_VPS_DEPLOYER_SSH_PASS }}
          script_stop: true
          script: |
            cp -r -f ${{ secrets.OMGIMGFLOW_API_TEMP_DEST}}/omgimgflow-api/* ${{ secrets.OMGIMGFLOW_API_DEST }}
            rm -rf ${{ secrets.HEALTHWISE_SSH_TEMP_DEST}}/omgimgflow-api
            sudo systemctl restart api-omgimageflow.service
